"""step2_auth_and_patient_management

Revision ID: 234ab7a262ec
Revises: dab26a747aa7
Create Date: 2026-09-05 12:06:27.045952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '234ab7a262ec'
down_revision: Union[str, Sequence[str], None] = 'dab26a747aa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_identifier', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('date_of_birth', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('symptoms', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('medical_conditions', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('allergies', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('current_medications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('other_information', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('anonymous_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_patients_anonymous_id'))
        batch_op.create_index(batch_op.f('ix_patients_anonymous_id'), ['anonymous_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_patient_identifier'), ['patient_identifier'], unique=True)
        batch_op.create_foreign_key('fk_patients_created_by_user_id', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('gender')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_status', sa.String(length=32), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_status')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=32), nullable=True))
        batch_op.drop_constraint('fk_patients_created_by_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patients_patient_identifier'))
        batch_op.drop_index(batch_op.f('ix_patients_name'))
        batch_op.drop_index(batch_op.f('ix_patients_created_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_patients_anonymous_id'))
        batch_op.create_index(batch_op.f('ix_patients_anonymous_id'), ['anonymous_id'], unique=1)
        batch_op.alter_column('anonymous_id',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.drop_column('created_by_user_id')
        batch_op.drop_column('other_information')
        batch_op.drop_column('current_medications')
        batch_op.drop_column('allergies')
        batch_op.drop_column('medical_conditions')
        batch_op.drop_column('symptoms')
        batch_op.drop_column('sex')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('name')
        batch_op.drop_column('patient_identifier')

    # ### end Alembic commands ###
