"""initial_medlens_tables

Revision ID: dab26a747aa7
Revises: 
Create Date: 2026-09-05 11:44:06.360598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dab26a747aa7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('license_number', sa.String(length=128), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('conflicts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('source_report_a_id', sa.String(length=36), nullable=False),
    sa.Column('source_report_b_id', sa.String(length=36), nullable=True),
    sa.Column('conflict_type', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_report_a_id'], ['medical_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_report_b_id'], ['medical_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conflicts_patient_id'), ['patient_id'], unique=False)

    op.create_table('lab_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('analyte_code', sa.String(length=64), nullable=True),
    sa.Column('raw_value', sa.String(length=128), nullable=False),
    sa.Column('numeric_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('reference_range', sa.String(length=128), nullable=True),
    sa.Column('flag', sa.String(length=32), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('provenance_page', sa.Integer(), nullable=True),
    sa.Column('provenance_bbox', sa.String(length=255), nullable=True),
    sa.Column('extraction_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['medical_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lab_results_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lab_results_test_name'), ['test_name'], unique=False)

    op.create_table('timeline_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('patient_id', sa.String(length=36), nullable=False),
    sa.Column('source_report_id', sa.String(length=36), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('facility', sa.String(length=255), nullable=True),
    sa.Column('clinician_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_report_id'], ['medical_reports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_timeline_events_patient_id'), ['patient_id'], unique=False)

    op.create_table('verification_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('report_id', sa.String(length=36), nullable=False),
    sa.Column('verified_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.Column('signature_hash', sa.String(length=128), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['medical_reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('verification_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_verification_records_report_id'), ['report_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_records_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_verification_records_verified_by_user_id'), ['verified_by_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verification_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_verification_records_verified_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_verification_records_status'))
        batch_op.drop_index(batch_op.f('ix_verification_records_report_id'))

    op.drop_table('verification_records')
    with op.batch_alter_table('timeline_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_events_patient_id'))
        batch_op.drop_index(batch_op.f('ix_timeline_events_event_date'))

    op.drop_table('timeline_events')
    with op.batch_alter_table('lab_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lab_results_test_name'))
        batch_op.drop_index(batch_op.f('ix_lab_results_report_id'))

    op.drop_table('lab_results')
    with op.batch_alter_table('conflicts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conflicts_patient_id'))

    op.drop_table('conflicts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
